name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/andrewtwydell/2024-rest-api:${{ github.sha }}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker tag ghcr.io/andrewtwydell/2024-rest-api:${{ github.sha }} ghcr.io/andrewtwydell/2024-rest-api:latest
          fi

      - name: Push the Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/andrewtwydell/2024-rest-api:${{ github.sha }}
          docker push ghcr.io/andrewtwydell/2024-rest-api:latest
